import { execFileSync } from "node:child_process";
import {
  copyFileSync,
  existsSync,
  lstatSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  realpathSync,
  renameSync,
  rmdirSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { basename, dirname, isAbsolute, join, parse, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

const PLUGIN_NAME = "icon-svg-select";
const CANDIDATE_PREFIX = `.${PLUGIN_NAME}-stage-`;
const BACKUP_PREFIX = `.${PLUGIN_NAME}-backup-`;
const GENERATED_MARKER = ".icon-svg-select-generated";
const GENERATED_MARKER_CONTENT = "Generated by npm run plugin:stage; safe to replace.\n";

export type DirectoryIdentity = {
  path: string;
  realPath: string;
  device: number;
  inode: number;
};

function pathSegments(path: string): string[] {
  const absolute = resolve(path);
  const root = parse(absolute).root;
  const remainder = relative(root, absolute);
  return remainder === "" ? [root] : [root, ...remainder.split(sep)];
}

/** Reject a symlink in any existing component before a staging write. */
export function assertDirectoryChainHasNoSymlink(path: string): void {
  if (!isAbsolute(path)) throw new Error(`Expected an absolute directory path, received "${path}".`);
  const [root, ...segments] = pathSegments(path);
  if (root === undefined) throw new Error(`Could not resolve directory path "${path}".`);
  let cursor = root;
  for (const segment of segments) {
    cursor = join(cursor, segment);
    const status = lstatSync(cursor);
    if (status.isSymbolicLink()) throw new Error(`Refusing to stage through symlink "${cursor}".`);
    if (!status.isDirectory()) throw new Error(`Expected directory "${cursor}".`);
  }
}

export function captureDirectoryIdentity(path: string): DirectoryIdentity {
  const absolutePath = resolve(path);
  assertDirectoryChainHasNoSymlink(absolutePath);
  const status = lstatSync(absolutePath);
  return {
    path: absolutePath,
    realPath: realpathSync(absolutePath),
    device: status.dev,
    inode: status.ino,
  };
}

function assertDirectoryIdentity(identity: DirectoryIdentity): void {
  const current = captureDirectoryIdentity(identity.path);
  if (
    current.realPath !== identity.realPath
    || current.device !== identity.device
    || current.inode !== identity.inode
  ) {
    throw new Error(`Refusing to operate after directory identity changed: "${identity.path}".`);
  }
}

function entryExists(path: string): boolean {
  try {
    lstatSync(path);
    return true;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return false;
    throw error;
  }
}

function assertDirectChild(target: string, parent: string, allowedPrefixes: readonly string[]): void {
  const absoluteTarget = resolve(target);
  const absoluteParent = resolve(parent);
  if (dirname(absoluteTarget) !== absoluteParent) {
    throw new Error(`Refusing to operate outside "${absoluteParent}": "${absoluteTarget}".`);
  }
  const name = basename(absoluteTarget);
  if (!allowedPrefixes.some((prefix) => prefix.endsWith("-") ? name.startsWith(prefix) : name === prefix)) {
    throw new Error(`Refusing to operate on unexpected staging path "${absoluteTarget}".`);
  }
}


/** Rename one owned direct child without accepting a changed or symlinked parent. */
export function renameOwnedDirectory(
  source: string,
  destination: string,
  parent: string,
  sourcePrefixes: readonly string[],
  destinationPrefixes: readonly string[],
  expectedParent?: DirectoryIdentity,
): void {
  assertDirectChild(source, parent, sourcePrefixes);
  assertDirectChild(destination, parent, destinationPrefixes);
  const parentIdentity = expectedParent ?? captureDirectoryIdentity(parent);
  assertDirectoryIdentity(parentIdentity);
  const sourceIdentity = captureDirectoryIdentity(source);
  if (entryExists(destination)) throw new Error(`Refusing to replace existing path "${destination}".`);
  assertDirectoryIdentity(parentIdentity);
  assertDirectoryIdentity(sourceIdentity);
  renameSync(source, destination);
}

/** Remove an owned generated tree without following symlinks inside it. */
export function removeOwnedTree(
  target: string,
  parent: string,
  allowedPrefixes: readonly string[],
  expectedParent?: DirectoryIdentity,
): void {
  assertDirectChild(target, parent, allowedPrefixes);
  const parentIdentity = expectedParent ?? captureDirectoryIdentity(parent);
  assertDirectoryIdentity(parentIdentity);
  if (!entryExists(target)) return;
  const targetIdentity = captureDirectoryIdentity(target);
  const guard = (): void => {
    assertDirectoryIdentity(parentIdentity);
    assertDirectoryIdentity(targetIdentity);
  };

  removeTreeContents(target, guard);
  guard();
  rmdirSync(target);
}

function removeTreeContents(directory: string, rootGuard: () => void): void {
  const directoryIdentity = captureDirectoryIdentity(directory);
  const guard = (): void => {
    rootGuard();
    assertDirectoryIdentity(directoryIdentity);
  };
  guard();
  for (const entry of readdirSync(directory)) {
    guard();
    const child = join(directory, entry);
    const status = lstatSync(child);
    if (status.isDirectory() && !status.isSymbolicLink()) {
      const childIdentity = captureDirectoryIdentity(child);
      removeTreeContents(child, guard);
      guard();
      assertDirectoryIdentity(childIdentity);
      rmdirSync(child);
    } else {
      guard();
      unlinkSync(child);
    }
  }
}

export function createLocalPluginVersion(baseVersion: string, now = new Date()): string {
  const versionWithoutBuild = baseVersion.replace(/\+.*/, "");
  const timestamp = now.toISOString().replace(/[-:]/g, "").replace(/\.\d{3}Z$/, "").replace("T", "-");
  return `${versionWithoutBuild}+codex.local-${timestamp}`;
}

/** Require an ownership marker, while accepting one pre-marker staged layout for migration. */
export function assertReplaceableStageDirectory(directory: string): void {
  const status = lstatSync(directory);
  if (status.isSymbolicLink()) throw new Error(`Refusing to replace symlink "${directory}".`);
  if (!status.isDirectory()) throw new Error(`Refusing to replace non-directory "${directory}".`);

  const markerPath = join(directory, GENERATED_MARKER);
  if (existsSync(markerPath)) {
    if (lstatSync(markerPath).isSymbolicLink()) throw new Error(`Refusing generated marker symlink "${markerPath}".`);
    if (readFileSync(markerPath, "utf8") !== GENERATED_MARKER_CONTENT) {
      throw new Error(`Refusing directory with an invalid generated marker: "${directory}".`);
    }
    return;
  }

  const packagePath = join(directory, "package.json");
  const manifestPath = join(directory, ".codex-plugin", "plugin.json");
  const legacyShape = existsSync(packagePath)
    && existsSync(manifestPath)
    && existsSync(join(directory, "dist"))
    && existsSync(join(directory, "node_modules"));
  if (!legacyShape) throw new Error(`Refusing to replace unowned directory "${directory}".`);
  const packageName = (JSON.parse(readFileSync(packagePath, "utf8")) as { name?: unknown }).name;
  const pluginName = (JSON.parse(readFileSync(manifestPath, "utf8")) as { name?: unknown }).name;
  if (packageName !== PLUGIN_NAME || pluginName !== PLUGIN_NAME) {
    throw new Error(`Refusing to replace unowned directory "${directory}".`);
  }
}

function writeLocalCachebuster(pluginDirectory: string): string {
  const manifestPath = join(pluginDirectory, ".codex-plugin", "plugin.json");
  const manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as { version?: unknown };
  if (typeof manifest.version !== "string") throw new Error("Plugin manifest has no string version.");
  const version = createLocalPluginVersion(manifest.version);
  manifest.version = version;
  writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, "utf8");
  return version;
}

export function stagePlugin(): { directory: string; version: string } {
  const workspace = realpathSync(resolve(dirname(fileURLToPath(import.meta.url)), ".."));
  const workspaceIdentity = captureDirectoryIdentity(workspace);

  const pluginsDirectory = join(workspace, "plugins");
  if (!entryExists(pluginsDirectory)) {
    assertDirectoryIdentity(workspaceIdentity);
    mkdirSync(pluginsDirectory);
  }
  const pluginsIdentity = captureDirectoryIdentity(pluginsDirectory);

  const stageDirectory = join(pluginsDirectory, PLUGIN_NAME);
  assertDirectChild(stageDirectory, pluginsDirectory, [PLUGIN_NAME]);
  assertDirectoryIdentity(pluginsIdentity);
  if (entryExists(stageDirectory)) assertReplaceableStageDirectory(stageDirectory);

  assertDirectoryIdentity(pluginsIdentity);
  const candidateDirectory = mkdtempSync(join(pluginsDirectory, CANDIDATE_PREFIX));
  const candidateIdentity = captureDirectoryIdentity(candidateDirectory);
  const realTemporaryRoot = realpathSync(tmpdir());
  const temporaryRootIdentity = captureDirectoryIdentity(realTemporaryRoot);
  assertDirectoryIdentity(temporaryRootIdentity);
  const packDirectory = mkdtempSync(join(realTemporaryRoot, `${PLUGIN_NAME}-pack-`));
  const packIdentity = captureDirectoryIdentity(packDirectory);
  let candidateExists = true;
  let backupDirectory: string | undefined;

  const assertCandidateSafe = (): void => {
    assertDirectoryIdentity(pluginsIdentity);
    assertDirectoryIdentity(candidateIdentity);
  };
  const assertPackSafe = (): void => {
    assertDirectoryIdentity(temporaryRootIdentity);
    assertDirectoryIdentity(packIdentity);
  };

  try {
    assertPackSafe();
    execFileSync("npm", ["pack", "--pack-destination", packDirectory], {
      cwd: workspace,
      stdio: "ignore",
    });
    assertPackSafe();
    const tarballs = readdirSync(packDirectory).filter((name) => name.endsWith(".tgz"));
    if (tarballs.length !== 1 || tarballs[0] === undefined) {
      throw new Error(`Expected one npm tarball, found ${tarballs.length}.`);
    }
    assertCandidateSafe();
    assertPackSafe();
    execFileSync("tar", ["-xzf", join(packDirectory, tarballs[0]), "-C", candidateDirectory, "--strip-components=1"]);
    assertCandidateSafe();
    assertPackSafe();

    // npm tarballs omit package-lock.json. Reintroduce it only for the
    // production install so the cached local plugin is byte-for-byte resolved
    // from the same dependency graph as development and CI.
    const candidateLock = join(candidateDirectory, "package-lock.json");
    assertCandidateSafe();
    copyFileSync(join(workspace, "package-lock.json"), candidateLock);
    assertCandidateSafe();
    execFileSync(
      "npm",
      [
        "ci",
        "--omit=dev",
        "--ignore-scripts",
        "--no-audit",
        "--no-fund",
        "--registry=https://registry.npmjs.org",
      ],
      { cwd: candidateDirectory, stdio: "inherit" },
    );
    assertCandidateSafe();
    unlinkSync(candidateLock);

    assertCandidateSafe();
    const version = writeLocalCachebuster(candidateDirectory);
    const cliVersion = execFileSync(process.execPath, [join(candidateDirectory, "dist", "adapters", "cli.js"), "--version"], {
      cwd: candidateDirectory,
      encoding: "utf8",
    }).trim();
    const packageVersion = (JSON.parse(readFileSync(join(candidateDirectory, "package.json"), "utf8")) as { version?: unknown }).version;
    if (cliVersion !== packageVersion) {
      throw new Error(`Staged CLI version "${cliVersion}" does not match package version "${String(packageVersion)}".`);
    }
    assertCandidateSafe();
    writeFileSync(join(candidateDirectory, GENERATED_MARKER), GENERATED_MARKER_CONTENT, "utf8");

    assertDirectoryIdentity(pluginsIdentity);
    if (entryExists(stageDirectory)) {
      backupDirectory = join(pluginsDirectory, `${BACKUP_PREFIX}${process.pid}-${Date.now()}`);
      assertDirectChild(backupDirectory, pluginsDirectory, [BACKUP_PREFIX]);
      if (entryExists(backupDirectory)) throw new Error(`Backup path already exists: "${backupDirectory}".`);
      renameOwnedDirectory(
        stageDirectory,
        backupDirectory,
        pluginsDirectory,
        [PLUGIN_NAME],
        [BACKUP_PREFIX],
        pluginsIdentity,
      );
    }

    try {
      renameOwnedDirectory(
        candidateDirectory,
        stageDirectory,
        pluginsDirectory,
        [CANDIDATE_PREFIX],
        [PLUGIN_NAME],
        pluginsIdentity,
      );
      candidateExists = false;
    } catch (error) {
      assertDirectoryIdentity(pluginsIdentity);
      if (backupDirectory !== undefined && !entryExists(stageDirectory)) {
        renameOwnedDirectory(
          backupDirectory,
          stageDirectory,
          pluginsDirectory,
          [BACKUP_PREFIX],
          [PLUGIN_NAME],
          pluginsIdentity,
        );
      }
      backupDirectory = undefined;
      throw error;
    }

    if (backupDirectory !== undefined) {
      removeOwnedTree(backupDirectory, pluginsDirectory, [BACKUP_PREFIX], pluginsIdentity);
      backupDirectory = undefined;
    }
    return { directory: stageDirectory, version };
  } finally {
    assertDirectoryIdentity(pluginsIdentity);
    if (candidateExists && entryExists(candidateDirectory)) {
      removeOwnedTree(candidateDirectory, pluginsDirectory, [CANDIDATE_PREFIX], pluginsIdentity);
    }
    if (backupDirectory !== undefined && entryExists(backupDirectory) && !entryExists(stageDirectory)) {
      renameOwnedDirectory(
        backupDirectory,
        stageDirectory,
        pluginsDirectory,
        [BACKUP_PREFIX],
        [PLUGIN_NAME],
        pluginsIdentity,
      );
    }
    removeOwnedTree(packDirectory, realTemporaryRoot, [`${PLUGIN_NAME}-pack-`], temporaryRootIdentity);
  }
}

if (resolve(process.argv[1] ?? "") === fileURLToPath(import.meta.url)) {
  const staged = stagePlugin();
  process.stdout.write(`staged ${staged.directory} (${staged.version})\n`);
}
